###
### default application configuration
###

# ================================================================================
# Spring
# ================================================================================
spring:

  # ==============================================================================
  # main
  # ==============================================================================
  main:
    showBanner: false


# ================================================================================
# server 
# ================================================================================
server:
  port: 8080


# ================================================================================
# management (Spring actuator)
# ================================================================================
management:
  port: 8081
  contextPath: /management
  addApplicationContextHeader: false


# ================================================================================
# logging
# ================================================================================
logging:
  level:
    io:  ERROR
    jp:  ERROR
    net: ERROR
    org: ERROR


# ================================================================================
# $name$ configuration
# ================================================================================
$name$:

  # ==============================================================================
  # build information 
  # ==============================================================================
  build:
    version: "\${version}"
    commit: "\${commit}"
    date: "\${date}"
